export const CONFIG = {
    WIDTH: 800,
    HEIGHT: 600,
    PLAYER_SPEED: 350,
    PLAYER_SHOOT_COOLDOWN: 250,
    ENEMY_BASE_SPEED: 130,
    ENEMY_SHOOT_DELAY: 1500,     // cada inimigo atira após esse tempo (ms)
    BULLET_SPEED: -450,
    ENEMY_BULLET_SPEED: 280,
    COIN_VALUE: 10,
    ENEMY_VALUE: 20,
    PLAYER_INVINCIBLE_DURATION: 1500,
    PLAYER_MAX_HEALTH: 3,
    SPAWN_ENEMY_DELAY: 1200,
    SPAWN_COIN_DELAY: 800,
    DIFFICULTY_INCREASE_INTERVAL: 10000,
    MIN_ENEMY_SPAWN_DELAY: 400,
};